jsx = "react-jsx"
jsxImportSource = "react"
logLevel = "debug"
telemetry = false

[loader]
".tsx" = "tsx"
".ts" = "ts"

[install]
auto = "auto"

[run]
bun = true
shell = "bun"

[define]
"globalThis.__REPLIT__" = "{}"